#!/usr/bin/env tsx
/**
 * sync-ai-context.ts
 *
 * Reads source AI context files and generates platform-specific rule files.
 * Run: npm run sync:context
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), '..');

const C = {
  reset: '\x1b[0m', green: '\x1b[32m', yellow: '\x1b[33m', cyan: '\x1b[36m', red: '\x1b[31m', bold: '\x1b[1m',
};

const SOURCES: Record<string, string> = {
  project: 'openspec/project.md',
  architecture: '.ai/ARCHITECTURE.md',
  conventions: '.ai/CONVENTIONS.md',
  guardrails: '.ai/GUARDRAILS.md',
  stack: '.ai/STACK.md',
};

function readSource(key: string): string {
  const filePath = path.join(ROOT, SOURCES[key]);
  if (!fs.existsSync(filePath)) {
    console.warn(`${C.yellow}⚠ Missing source: ${SOURCES[key]}${C.reset}`);
    return `<!-- Source not found: ${SOURCES[key]} -->`;
  }
  return fs.readFileSync(filePath, 'utf8').trim();
}

function generatedWarning(platform: string): string {
  return `<!-- ⚠️  AUTO-GENERATED — Do NOT edit this file directly.
     Source: openspec/project.md + .ai/  directory
     Regenerate: npm run sync:context
     Platform: ${platform}
-->`;
}

function buildFullContext(sources: Record<string, string>): string {
  return `# AI Context\n\n${sources.project}\n\n---\n\n# Architecture Reference\n\n${sources.architecture}\n\n---\n\n# Coding Conventions\n\n${sources.conventions}\n\n---\n\n# Guardrails & Rules\n\n${sources.guardrails}\n\n---\n\n# Tech Stack\n\n${sources.stack}\n`;
}

function buildCursorContent(sources: Record<string, string>): string {
  return `---\ndescription: Project rules\nglobs: ["**/*.ts", "**/*.tsx", "**/*.sql", "**/*.json"]\nalwaysApply: true\n---\n\n${generatedWarning('Cursor')}\n\n# Project Rules\n\n${sources.project}\n\n---\n\n${sources.guardrails}\n\n---\n\n${sources.conventions}\n\n---\n\n${sources.stack}\n`;
}

function buildWindsurfContent(sources: Record<string, string>): string {
  return `${generatedWarning('Windsurf')}\n\n# AI Rules\n\n${sources.project}\n\n---\n\n${sources.guardrails}\n\n---\n\n${sources.conventions}\n`;
}

function buildCopilotContent(sources: Record<string, string>): string {
  return `${generatedWarning('GitHub Copilot')}\n\n# Copilot Instructions\n\n${sources.project}\n\n---\n\n${sources.guardrails}\n\n---\n\n${sources.architecture}\n`;
}

function writeIfChanged(targetPath: string, content: string): 'written' | 'unchanged' {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (fs.existsSync(targetPath) && fs.readFileSync(targetPath, 'utf8') === content) return 'unchanged';
  fs.writeFileSync(targetPath, content, 'utf8');
  return 'written';
}

const OUTPUTS = [
  { label: 'Cursor', path: '.cursor/rules/orchable.mdc', content: buildCursorContent },
  { label: 'Windsurf', path: '.windsurfrules', content: buildWindsurfContent },
  { label: 'Antigravity', path: '.agents/rules/project-context.md', content: (s: Record<string, string>) => `${generatedWarning('Antigravity')}\n\n${buildFullContext(s)}` },
  { label: 'Copilot', path: '.github/copilot-instructions.md', content: buildCopilotContent },
];

console.log(`${C.bold}${C.cyan}🔄 sync-ai-context${C.reset} — reading source files...\n`);
const sources: Record<string, string> = {};
let hasError = false;

for (const [key, relPath] of Object.entries(SOURCES)) {
  const filePath = path.join(ROOT, relPath);
  if (!fs.existsSync(filePath)) {
    console.error(`${C.red}❌ Source missing: ${relPath}${C.reset}`);
    hasError = true;
  } else {
    sources[key] = fs.readFileSync(filePath, 'utf8').trim();
    console.log(`  ${C.green}✓${C.reset} read  ${relPath}`);
  }
}

if (hasError) console.warn(`\n${C.yellow}Warning: some source files are missing. Continuing anyway...${C.reset}`);

console.log(`\n${C.bold}Writing platform files:${C.reset}`);
let written = 0, unchanged = 0;

for (const target of OUTPUTS) {
  const result = writeIfChanged(path.join(ROOT, target.path), target.content(sources));
  if (result === 'written') {
    console.log(`  ${C.green}✅ written  ${target.path}${C.reset} (${target.label})`);
    written++;
  } else {
    console.log(`  ${C.yellow}–  unchanged ${target.path}${C.reset} (${target.label})`);
    unchanged++;
  }
}
console.log(`\n${C.bold}Done.${C.reset} ${written} written, ${unchanged} unchanged.\n`);
